#!/bin/bash
set -e

# Codex Auto PR Generator
# Usage: ./scripts/auto-pr.sh [task-file-path] [options]

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Functions
log_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

log_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

log_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

log_error() {
    echo -e "${RED}❌ $1${NC}"
}

# Check prerequisites
check_prerequisites() {
    log_info "Checking prerequisites..."

    # Check git
    if ! command -v git &> /dev/null; then
        log_error "git is not installed"
        exit 1
    fi

    # Check gh CLI
    if ! command -v gh &> /dev/null; then
        log_error "gh CLI is not installed. Install: https://cli.github.com"
        exit 1
    fi

    # Check gh auth
    if ! gh auth status &> /dev/null; then
        log_error "gh CLI is not authenticated. Run: gh auth login"
        exit 1
    fi

    log_success "All prerequisites met"
}

# Parse task file
parse_task_file() {
    local task_file="$1"

    if [ ! -f "$task_file" ]; then
        log_error "Task file not found: $task_file"
        exit 1
    fi

    log_info "Parsing task file: $task_file"

    # Extract title from first line
    TASK_TITLE=$(head -1 "$task_file" | sed 's/^# Task: //')

    # Extract goal from ## 1. Goal section
    TASK_GOAL=$(awk '/## 1\. Goal/,/## 2\./ {print}' "$task_file" | sed -n '2p' | sed 's/^[*-] //')

    # Extract brief name for branch
    TASK_BRIEF=$(basename "$task_file" .md | sed 's/codex-[0-9]*-//')

    log_success "Task title: $TASK_TITLE"
    log_success "Task brief: $TASK_BRIEF"
}

# Create branch
create_branch() {
    local branch_name="feature/$TASK_BRIEF"

    log_info "Creating branch: $branch_name"

    # Check if branch already exists
    if git show-ref --verify --quiet refs/heads/"$branch_name"; then
        log_warning "Branch already exists: $branch_name"
        read -p "Delete and recreate? (y/n) " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            git branch -D "$branch_name"
        else
            log_error "Aborted"
            exit 1
        fi
    fi

    git checkout -b "$branch_name"
    log_success "Branch created: $branch_name"

    BRANCH_NAME="$branch_name"
}

# Commit changes
commit_changes() {
    log_info "Committing changes..."

    # Check if there are changes
    if git diff --quiet && git diff --cached --quiet; then
        log_error "No changes to commit"
        exit 1
    fi

    # Show changes
    echo ""
    log_info "Changed files:"
    git status --short

    # Add all changes
    git add .

    # Generate commit message
    local commit_msg="feat: $TASK_TITLE

$TASK_GOAL

🤖 Generated with [Claude Code](https://claude.com/claude-code)

Co-Authored-By: Claude Sonnet 4.5 <noreply@anthropic.com>"

    # Commit
    git commit -m "$commit_msg"

    log_success "Changes committed"
}

# Push to remote
push_to_remote() {
    log_info "Pushing to remote..."

    git push -u origin "$BRANCH_NAME"

    log_success "Pushed to remote: $BRANCH_NAME"
}

# Generate PR body
generate_pr_body() {
    local task_file="$1"

    # Get changed files
    local changed_files=$(git diff --name-status origin/main... | awk '{print "- " $1 ": `" $2 "`"}')

    # Generate PR body
    cat > /tmp/pr_body.md <<EOF
## Summary
$TASK_GOAL

## Changes
$changed_files

## Task File
Implemented from: \`$task_file\`

## Test Plan
See task file for detailed test commands.

\`\`\`bash
# Frontend
cd apps/doctor-dashboard
pnpm test

# Backend
cd server
uv run pytest
\`\`\`

## Security Review
- [ ] At-rest encryption applied
- [ ] RBAC implemented
- [ ] PII logging prohibited
- [ ] No environment variables exposed

## Related Issues
Closes #[issue-number]

---

🤖 Auto-generated PR from Codex

Co-Authored-By: Claude Sonnet 4.5 <noreply@anthropic.com>
EOF

    PR_BODY_FILE="/tmp/pr_body.md"
}

# Create PR
create_pr() {
    log_info "Creating pull request..."

    # Generate PR body
    generate_pr_body "$TASK_FILE"

    # Create PR
    local pr_title="feat: $TASK_TITLE"

    gh pr create \
        --title "$pr_title" \
        --body-file "$PR_BODY_FILE" \
        --base main \
        --head "$BRANCH_NAME" \
        --label "autogenerated,needs-review"

    log_success "Pull request created!"

    # Get PR URL
    PR_URL=$(gh pr view --json url -q .url)
    echo ""
    log_success "PR URL: $PR_URL"
}

# Main
main() {
    echo ""
    log_info "🤖 Codex Auto PR Generator"
    echo ""

    # Parse arguments
    TASK_FILE="${1:-}"
    DRAFT_MODE="${2:-}"

    # Find task file if not provided
    if [ -z "$TASK_FILE" ]; then
        log_info "No task file specified. Searching for latest task..."
        TASK_FILE=$(find docs/tasks -name "codex-*.md" -type f -printf '%T@ %p\n' | sort -nr | head -1 | cut -d' ' -f2-)

        if [ -z "$TASK_FILE" ]; then
            log_error "No task file found in docs/tasks/"
            exit 1
        fi

        log_info "Found: $TASK_FILE"
    fi

    # Check prerequisites
    check_prerequisites

    # Parse task file
    parse_task_file "$TASK_FILE"

    # Create branch
    create_branch

    # Commit changes
    commit_changes

    # Push to remote
    push_to_remote

    # Create PR
    create_pr

    echo ""
    log_success "🎉 Done! PR created successfully"
    echo ""
    log_info "Next steps:"
    echo "  1. Review the PR: $PR_URL"
    echo "  2. Wait for CI to complete"
    echo "  3. Request review from team members"
    echo "  4. Merge when approved"
    echo ""
}

# Run
main "$@"
